name: MegaETH Daily Interactions

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install web3==6.11.1 requests==2.31.0 eth-utils==2.3.0

      - name: Create wallet configuration
        run: echo "${{ secrets.WALLETS_JSON }}" > wallets.json

      - name: Run MegaETH Automation
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
          WEB3_PROVIDER_URI: "https://rpc.testnet.megaeth.io"
          WEB3_FALLBACK_URI: "http://rpc.megaeth.io"
          RETRY_COUNT: "3"
          RETRY_DELAY: "5"
        run: python mega_eth_automation.py

      - name: Cleanup sensitive data
        if: always()
        run: rm -f wallets.json
